# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true
markdown:            kramdown 

# Setup
title:               Josh's Web
tagline:             Josh Syu
url:                 http://getpoole.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Josh Syu
  url:               https://twitter.com/joshsyu
  email:             joshsyu.tw@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

kramdown:
    input: GFM

#PAGINATION
gems: 
    - jekyll-paginate
    - jekyll-gist
paginate: 5
paginate_path: "page:num"

